x-api_template: &api_template
  image: "lucasvsouza28/rinha-bun"
  ports:
    - "3000:3000"
  restart: always
  environment:
    - PORT=3000
    - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    - REDIS_URL=redis://redis:6379
    - POSTGRES_URL=postgres://postgres:postgres@db:5432/rinha
  networks:
    - rinha-backend
    - payment-processor
  depends_on:
    redis:
      condition: service_healthy

services:
  db:
    image: "postgres:17-alpine"
    networks:
      - rinha-backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - rinha-backend
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 20MB
    
  api-1:
    <<: *api_template
    hostname: api-1
    ports:
      - "9998:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100MB

  api-2:
    <<: *api_template
    hostname: api-2
    ports:
      - "9997:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100MB
  # api-3:
  #   <<: *api_template
  #   hostname: api-2
  #   ports:
  #     - "9996:3000"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.3'
  #         memory: 50MB

  nginx:
    image: nginx:alpine
    # container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api-1
      - api-2
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "60MB"

networks:
  rinha-backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis_data:
    driver: local
