x-api_template: &api_template
  image: "lucasvsouza28/rinha-bun"
  #ports:
    #- "9998:9998"
  restart: always
  environment:
    #- PORT=9998
    - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
    - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    - REDIS_URL=redis://redis:6379
  networks:
    - rinha-bun
    - payment-processor
  depends_on:
    redis:
      condition: service_healthy

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - rinha-bun
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 80MB
    
  api-1:
    <<: *api_template
    ports:
      - "9998:9998"
    environment:
      - PORT=9998
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100MB
  api-2:
    <<: *api_template
    ports:
      - "9997:9997"
    environment:
      - PORT=9997
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100MB
  
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "30MB"
    networks:
      - rinha-bun

networks:
  rinha-bun:
    driver: bridge
  payment-processor:
    driver: bridge
    external: true

volumes:
  redis_data:
    driver: local
